# Copyright FUJITSU LIMITED 2015.

- name: /personium/personium-esgclog のディレクトリを作成
  file: "state=directory path=/personium/personium-esgclog owner=root group=root"

- name: /etc/init/esgclog.conf の配備
  copy: src=./resource/es/etc/init/esgclog.conf dest=/etc/init/esgclog.conf owner=root group=root mode=644

- name: /personium/personium-esgclog/printFullGC.awk の配備
  copy: src=./resource/es/personium/personium-esgclog/printFullGC.awk dest=/personium/personium-esgclog/printFullGC.awk owner=root group=root mode=744

- name: /personium/personium-esgclog/esGCLog.sh の配備
  copy: src=./resource/es/personium/personium-esgclog/esGCLog.sh dest=/personium/personium-esgclog/esGCLog.sh owner=root group=root mode=744

- name: /etc/logrotate.d/es-fullgc の配備
  copy: src=./resource/es/etc/logrotate.d/es-fullgc dest=/etc/logrotate.d/es-fullgc owner=root group=root mode=0644

- name: initctl configuration 起動状態確認
  shell: "/sbin/initctl list | grep esgclog"
  register: esgclog_initctl_list

- name: initctl esgclog 停止
  command: "/sbin/initctl stop esgclog"
  when: '"esgclog start/running" in esgclog_initctl_list.stdout'

- name: initctl configuration 再読み込み
  command: "/sbin/initctl reload-configuration"

- name: initctl esgclog 起動
  command: "/sbin/initctl start esgclog"
