# Copyright FUJITSU LIMITED 2015-2017.

- name: /personium を作成
  file: state=directory path=/personium owner=root group=root mode=0755


#- name: /opt/nfs_piolog/personium-core を作成
#  file: state=directory path=/opt/nfs_piolog/personium-core owner=root group=root mode=0755

#- name: /opt/nfs_piolog/personium-core/log を作成
#  file: state=directory path=/opt/nfs_piolog/personium-core/log owner=personium group=personium mode=0755

#- name: /personium/personium-core を作成
#  file: state=directory path=/personium/personium-core owner=personium group=personium mode=0755

#- name: /personium/personium-core に /opt/nfs_piolog/personium-core/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/personium-core/log dest=/personium/personium-core/log owner=personium group=personium mode=0777

#- name: /opt/nfs_piolog/personium-engine を作成
#  file: state=directory path=/opt/nfs_piolog/personium-engine owner=root group=root mode=0755

#- name: /opt/nfs_piolog/personium-engine/log を作成
#  file: state=directory path=/opt/nfs_piolog/personium-engine/log owner=personium group=personium mode=0755

#- name: /personium/personium-engine を作成
#  file: state=directory path=/personium/personium-engine owner=personium group=personium mode=0755

#- name: /personium/personium-engine に /opt/nfs_piolog/personium-engine/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/personium-engine/log dest=/personium/personium-engine/log owner=personium group=personium mode=0777


#- name: /opt/nfs_piolog/logback を作成
#  file: state=directory path=/opt/nfs_piolog/logback owner=root group=root mode=0755

#- name: /opt/nfs_piolog/logback/log を作成
#  file: state=directory path=/opt/nfs_piolog/logback/log owner=personium group=personium mode=0755

- name: /personium/logback を作成
  file: state=directory path=/personium/logback owner=personium group=personium mode=0755

- name: /personium/logback/log を作成
  file: state=directory path=/personium/logback/log owner=personium group=personium mode=0755

#- name: /personium/logback に /opt/nfs_piolog/logback/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/logback/log dest=/personium/logback/log owner=personium group=personium mode=0777


- name: /personium_nfs を作成
  file: state=directory path=/personium_nfs owner=root group=root mode=0755


- name: /opt/nfs_webdav/personium-core を作成
  file: state=directory path=/opt/nfs_webdav/personium-core owner=root group=root mode=0755

- name: /opt/nfs_webdav/personium-core/dav を作成
  file: state=directory path=/opt/nfs_webdav/personium-core/dav owner=personium group=personium mode=0755

- name: /opt/nfs_webdav/personium-core/eventlog を作成
  file: state=directory path=/opt/nfs_webdav/personium-core/eventlog owner=personium group=personium mode=0755

- name: /opt/nfs_webdav/personium-core/barInstall を作成
  file: state=directory path=/opt/nfs_webdav/personium-core/barInstall owner=personium group=personium mode=0755

- name: /personium_nfs/personium-core を作成
  file: state=directory path=/personium_nfs/personium-core owner=personium group=personium mode=0755

- name: /personium_nfs/personium-core に /opt/nfs_webdav/personium-core/dav の symlink を作成
  file: state=link src=/opt/nfs_webdav/personium-core/dav dest=/personium_nfs/personium-core/dav owner=personium group=personium mode=0777

- name: /personium_nfs/personium-core に /opt/nfs_webdav/personium-core/eventlog の symlink を作成
  file: state=link src=/opt/nfs_webdav/personium-core/eventlog dest=/personium_nfs/personium-core/eventlog owner=personium group=personium mode=0777

- name: /personium_nfs/personium-core に /opt/nfs_webdav/personium-core/barInstall の symlink を作成
  file: state=link src=/opt/nfs_webdav/personium-core/barInstall dest=/personium_nfs/personium-core/barInstall owner=personium group=personium mode=0777
