# Copyright FUJITSU LIMITED 2015-2017.

- name: JDKのダウンロード
  command: 'wget -q -O /usr/src/jdk1.8.0_121.tar.gz --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz creates=/usr/src/jdk1.8.0_121.tar.gz'

- name: JDKのアーカイブを解凍
  command: "tar -xzf /usr/src/jdk1.8.0_121.tar.gz -C /usr/src creates=/usr/src/jdk1.8.0_121"

- name: JDKのオーナーをroot/rootに変更
  file: "state=directory path=/usr/src/jdk1.8.0_121 owner=root group=root recurse=yes"

- name: JDKを /opt に配備
  command: "mv /usr/src/jdk1.8.0_121 /opt creates=/opt/jdk1.8.0_121"

- name: /opt/jdk1.8.0_121 に /opt/jdk のシンボリックリンクを作成
  file: "state=link src=/opt/jdk1.8.0_121 dest=/opt/jdk"

- name: /root/.bashrc に JAVAのEXPORTを追加
  copy: src=./resource/common/etc/bashrc dest=/etc/bashrc owner=root group=root mode=0644
