# Copyright FUJITSU LIMITED 2015.

- name: secret16の採取
  command: cat /personium/personium-core/conf/token.key
  register: secret16

- name: saltの採取
  command: cat /personium/personium-core/conf/salt.key
  register: salt

- name: clear master token
  set_fact: master_token=""

- name: personium-unit-config.properties の配備
  template: src=./resource/ap/personium/personium-core/conf/18888/personium-unit-config.properties.j2 dest=/personium/personium-core/conf/18888/personium-unit-config.properties owner=root group=root mode=0644

- name: restart tomcat
  service: name=tomcat state=restarted

